--- #Install and configure Consul

- hosts: '{{ myhosts }}'
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: '{{ gather }}'
  vars:
    myhosts: client
    gather: no
    with_items: "{{ item }}"
    consul_ver: 0.9.0  
  
  roles:
   - role: dependencies
#
   - role: configure_consul
#
   - role: pm2_service

#  tasks:
#    - debug: var=ansible_all_ipv4_addresses
#    - debug: var=ansible_default_ipv4.address 
#    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
#    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv6']['address']
