--- #Install and configure Consul

- hosts: '{{ myhosts }}'
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: '{{ gather }}'
  vars:
    myhosts: client
    gather: no
    with_items: "{{ item }}"
    consul_ver: 0.9.0  
  
#--- #Play Starts
  
  tasks: 
  
#--- #Update apt-repos
  - name: Update all packages
    apt:
     update_cache: yes
  
#--- #Install dependencies
  - name: Install dependencies pkg's
    apt: name={{ item }} state=latest
    #apt: name: "{{ item }}" state: absent
    with_items:
       - unzip
       - npm
#    register: result
#  - debug: var=result

  - name: Download consul 
    get_url:
      url: https://releases.hashicorp.com/consul/0.9.0/consul_0.9.0_linux_amd64.zip
#      url: https://releases.hashicorp.com/consul/'{{ consul_ver }}\'/consul_'{{ consul_ver }}\'_linux_amd64.zip
      dest: /usr/local/bin/consul.zip
        
  - name: Extract consul zip directory
    unarchive:
      src: /usr/local/bin/consul.zip
      dest: /usr/local/bin/
      remote_src: yes

  - name: Clean artifact path
    file:
      state: absent
      path: /usr/local/bin/consul.zip

  roles:
   - role: configure_consul
